/* AUTO-GENERATED by scripts/generate-site-map.mjs. Do not hand-edit. */
export const GENERATED_SITE_MAP = {
  "generatedAt": "source",
  "menuRoutes": [
    "/admin/boshqaruv",
    "/admin/obyektlar",
    "/admin/holat",
    "/admin/f2-tayyorlash",
    "/admin/f2-tarix",
    "/admin/nakopitelniy",
    "/admin/m29",
    "/admin/aosr",
    "/admin/f2",
    "/admin/smeta-narxlash",
    "/admin/oferta",
    "/admin/narx-manbalari",
    "/admin/narx-dalil",
    "/admin/nakrutka",
    "/admin/narxlar",
    "/admin/loyiha",
    "/admin/shartnoma-liniya",
    "/admin/documents",
    "/admin/hujjat-nazorat",
    "/admin/participants",
    "/admin/crm",
    "/admin/dashboard",
    "/admin/moliya",
    "/admin/logistika",
    "/admin/zayavka",
    "/admin/erp",
    "/admin/mindmap",
    "/admin/tokenlar",
    "/admin/kompaniya",
    "/admin/hujjat-dizayn",
    "/admin/tizim-sozlama",
    "/admin/system-control",
    "/admin/ai-agentlar",
    "/admin/sayt-xaritasi",
    "/admin/storage",
    "/admin/fayl-boglash",
    "/admin/korzinka",
    "/admin/buxgalteriya",
    "/admin/ierarxiya",
    "/admin/monitoring",
    "/admin/shaxsiy-smeta",
    "/admin/supabase",
    "/admin/tezlik"
  ],
  "appRouteSegments": [
    "/",
    "/admin",
    "dashboard",
    "obyektlar",
    "loyiha",
    "holat",
    "holat/:id",
    "fakt",
    "f2",
    "f2-eski",
    "f2-tayyorlash",
    "tokenlar",
    "boshqaruv",
    "hujjat-dizayn",
    "shartnoma-liniya",
    "nakopitelniy",
    "m29",
    "nakrutka",
    "narx-manbalari",
    "narx-dalil",
    "f2-tarix",
    "smeta-narxlash",
    "oferta",
    "buxgalteriya",
    "shartnomalar",
    "fakturalar",
    "sklad",
    "narxlar",
    "ierarxiya",
    "monitoring",
    "sozlamalar",
    "fayl-boglash",
    "hujjatlar",
    "shaxsiy-smeta",
    "supabase",
    "tezlik",
    "storage",
    "mindmap",
    "documents",
    "hujjat-nazorat",
    "participants",
    "system-control",
    "sayt-xaritasi",
    "ai-agentlar",
    "kompaniya",
    "_demo/documents",
    "_demo/participants",
    "_demo/system-control",
    "test",
    "portfel",
    "moliya",
    "logistika",
    "crm",
    "sozlama",
    "xodimlar",
    "korzinka",
    "xarita",
    "kontragent",
    "saqlash",
    "smeta",
    "daraxt",
    "tolov",
    "zayavka",
    "f2native",
    "faktura",
    "erp",
    "hisobot",
    "tizim",
    "aosr",
    "kadrlar",
    "texnika",
    "taminot",
    "sifat",
    "tizim-sozlama",
    "shartnoma",
    "kalkulyator",
    "*",
    "/boss",
    "eski"
  ],
  "readTables": [
    "obyektlar",
    "holat",
    "v_sklad_nomlar",
    "t2_kompaniya",
    "t2_obyekt",
    "t2_obyekt_jami",
    "t2_daraxt",
    "t2_qator",
    "t2_narx",
    "t2_manba",
    "t2_xom",
    "t2_lrv",
    "t2_kozgu",
    "t2_ozgarish",
    "t2_sozlama",
    "t2_akt",
    "t2_akt_qator",
    "t2_akt_reestr",
    "t2_qator_holat",
    "t2_faktura",
    "t2_ish_turi",
    "t2_shaxsiy_smeta",
    "v_erp_kadrlar_dashboard",
    "v_erp_texnika_dashboard",
    "v_erp_taminot_dashboard",
    "v_erp_sifat_dashboard",
    "t2_grafik_holat",
    "v_boss_init",
    "v_boss_data",
    "t2_birja_rfq",
    "t2_birja_taklif",
    "t2_sklad_qoldiq",
    "t2_sklad_harakat",
    "t2_narx_markaz",
    "t2_topilmaganlar",
    "t2_narx_sana",
    "t2_narx_qol_xavf",
    "t2_f2_kat_oy",
    "t2_f2_tafsilot",
    "t2_viborka",
    "t2_viborka_qabul",
    "t2_viborka_holat",
    "t2_shartnoma",
    "t2_shartnoma_bog",
    "t2_nakrutka",
    "t2_qoshimcha_ish",
    "t2_obyekt_nakrutka",
    "t2_tolov",
    "t2_xarajat",
    "t2_bux_dashboard",
    "t2_debitor_aging",
    "t2_bux_umumiy",
    "t2_aosr_reestr",
    "t2_aosr_coverage",
    "t2_aosr_reestr_v2",
    "t2_lab_protokol_reestr",
    "t2_kompaniya_logo",
    "t2_nakrutka_podval_royxat",
    "t2_narx_manba_royxat",
    "t2_narx_manba_qator",
    "t2_narx_taklif",
    "t2_narx_dalil_holat",
    "t2_platforma_narx_manba",
    "t2_platforma_narx_manba_qator",
    "t2_korzinka",
    "t2_audit_reestr",
    "t2_obyekt_hujjat_royxat",
    "t2_sklad_royxat",
    "t2_kadr_royxat",
    "t2_texnika_royxat",
    "t2_loyiha_royxat",
    "t2_loyiha_qatnashchilar_royxat",
    "t2_kontragent_royxat",
    "t2_azolik_royxat",
    "t2_material_alias_royxat",
    "t2_zayavka_royxat",
    "t2_hodisa_lenta",
    "t2_papka_daraxt",
    "t2_hujjat_turi",
    "t2_overbilling_radar",
    "t2_sklad_konsolidatsiya"
  ],
  "writeActions": [
    {
      "amal": "qoshimcha_ish_yarat_v1",
      "rpc": "t2_qoshimcha_ish_yarat_v1"
    },
    {
      "amal": "fakt_smetadan_tashqari_v1",
      "rpc": "t2_fakt_smetadan_tashqari_v1"
    },
    {
      "amal": "ish_turi_saqla_v1",
      "rpc": "t2_ish_turi_saqla_v1"
    },
    {
      "amal": "ish_abc_saqla_v1",
      "rpc": "t2_ish_abc_saqla_v1"
    },
    {
      "amal": "ish_abc_ochir_v1",
      "rpc": "t2_ish_abc_ochir_v1"
    },
    {
      "amal": "ish_abc_tahrir_v1",
      "rpc": "t2_ish_abc_tahrir_v1"
    },
    {
      "amal": "shartnoma_saqla_v2",
      "rpc": "t2_shartnoma_saqla_v2"
    },
    {
      "amal": "token_sarfla_v1",
      "rpc": "t2_token_sarfla_v1"
    },
    {
      "amal": "token_qaytar_v1",
      "rpc": "t2_token_qaytar_v1"
    },
    {
      "amal": "tolov_sorov_yarat_v1",
      "rpc": "t2_tolov_sorov_yarat_v1"
    },
    {
      "amal": "token_toldir_v1",
      "rpc": "t2_token_toldir_v1"
    },
    {
      "amal": "obuna_belgila_v1",
      "rpc": "t2_obuna_belgila_v1"
    },
    {
      "amal": "demo_manba_belgila_v1",
      "rpc": "t2_demo_manba_belgila_v1"
    },
    {
      "amal": "zamena_ish_yarat_v1",
      "rpc": "t2_zamena_ish_yarat_v1"
    },
    {
      "amal": "resurs_bola_qosh_v1",
      "rpc": "t2_resurs_bola_qosh_v1"
    },
    {
      "amal": "ish_resurslar_bilan_yarat_v1",
      "rpc": "t2_ish_resurslar_bilan_yarat_v1"
    },
    {
      "amal": "catalog_observation_yoz_v1",
      "rpc": "t2_catalog_observation_yoz_v1"
    },
    {
      "amal": "smeta_narxla_res",
      "rpc": "t2_smeta_narxla_res_v1"
    },
    {
      "amal": "qator_tahrir",
      "rpc": "t2_qator_tahrir"
    },
    {
      "amal": "qator_qosh",
      "rpc": "t2_qator_qosh"
    },
    {
      "amal": "akt_yarat",
      "rpc": "t2_akt_yarat"
    },
    {
      "amal": "akt_yarat_v2",
      "rpc": "t2_akt_yarat_v2"
    },
    {
      "amal": "price_basis_yarat",
      "rpc": "t2_price_basis_yarat_v1"
    },
    {
      "amal": "f2_import_job_yarat",
      "rpc": "t2_f2_import_job_yarat_v1"
    },
    {
      "amal": "f2_import_job_ilgarilash",
      "rpc": "t2_f2_import_job_ilgarilash_v1"
    },
    {
      "amal": "f2_import_job_recover",
      "rpc": "t2_f2_import_job_recover_v1"
    },
    {
      "amal": "f2_import_job_cancel",
      "rpc": "t2_f2_import_job_cancel_v1"
    },
    {
      "amal": "f2_import_draft_saqla",
      "rpc": "t2_f2_import_draft_saqla_v1"
    },
    {
      "amal": "akt_lifecycle_transition_v1",
      "rpc": "t2_akt_lifecycle_transition_v1"
    },
    {
      "amal": "akt_correction_create_v1",
      "rpc": "t2_akt_correction_create_v1"
    },
    {
      "amal": "akt_tasdiqlash",
      "rpc": "t2_akt_tasdiqlash"
    },
    {
      "amal": "akt_bekor",
      "rpc": "t2_akt_bekor"
    },
    {
      "amal": "narx_belgila",
      "rpc": "t2_narx_belgila"
    },
    {
      "amal": "narx_sana_qosh",
      "rpc": "t2_narx_sana_qosh"
    },
    {
      "amal": "skladga_yozish",
      "rpc": "t2_skladga_yozish"
    },
    {
      "amal": "faktura_yoz",
      "rpc": "t2_faktura_yoz"
    },
    {
      "amal": "ish_turi_yoz",
      "rpc": "t2_ish_turi_yoz"
    },
    {
      "amal": "shaxsiy_smeta_yarat",
      "rpc": "t2_shaxsiy_smeta_yarat"
    },
    {
      "amal": "erp_amal",
      "rpc": "t2_erp_amal"
    },
    {
      "amal": "grafik_yangilash",
      "rpc": "t2_grafik_yangilash"
    },
    {
      "amal": "grafik_sozlama_saqla",
      "rpc": "t2_grafik_sozlama_saqla"
    },
    {
      "amal": "boss_tahlil_boshla",
      "rpc": "t2_boss_tahlil_boshla"
    },
    {
      "amal": "sozlama_saqla",
      "rpc": "t2_sozlama_saqla"
    },
    {
      "amal": "tizim_amal",
      "rpc": "t2_tizim_amal"
    },
    {
      "amal": "xato_yoz",
      "rpc": "t2_xato_yoz"
    },
    {
      "amal": "kirish_amal",
      "rpc": "t2_kirish_amal"
    },
    {
      "amal": "taklif_yubor",
      "rpc": "t2_taklif_yubor"
    },
    {
      "amal": "taklif_qabul",
      "rpc": "t2_taklif_qabul"
    },
    {
      "amal": "birja_rfq_yarat",
      "rpc": "t2_birja_rfq_yarat"
    },
    {
      "amal": "birja_taklif_ber",
      "rpc": "t2_birja_taklif_ber"
    },
    {
      "amal": "viborka_smetadan_toldir",
      "rpc": "t2_viborka_smetadan_toldir"
    },
    {
      "amal": "viborka_qabul_yoz",
      "rpc": "t2_viborka_qabul_yoz"
    },
    {
      "amal": "shartnoma_saqla",
      "rpc": "t2_shartnoma_saqla"
    },
    {
      "amal": "shartnoma_ochir",
      "rpc": "t2_shartnoma_ochir"
    },
    {
      "amal": "shartnoma_bog_saqla",
      "rpc": "t2_shartnoma_bog_saqla"
    },
    {
      "amal": "nakrutka_saqla",
      "rpc": "t2_nakrutka_saqla"
    },
    {
      "amal": "tolov_yoz",
      "rpc": "t2_tolov_yoz"
    },
    {
      "amal": "tolov_tahrir",
      "rpc": "t2_tolov_tahrir"
    },
    {
      "amal": "tolov_ochir",
      "rpc": "t2_tolov_ochir"
    },
    {
      "amal": "xarajat_yoz",
      "rpc": "t2_xarajat_yoz"
    },
    {
      "amal": "xarajat_tahrir",
      "rpc": "t2_xarajat_tahrir"
    },
    {
      "amal": "xarajat_ochir",
      "rpc": "t2_xarajat_ochir"
    },
    {
      "amal": "korzinkaga_tashlash",
      "rpc": "t2_korzinkaga_tashlash"
    },
    {
      "amal": "korzinkadan_tiklash",
      "rpc": "t2_korzinkadan_tiklash"
    },
    {
      "amal": "butunlay_ochirish",
      "rpc": "t2_butunlay_ochirish"
    },
    {
      "amal": "obyekt_yangila",
      "rpc": "t2_obyekt_yangila"
    },
    {
      "amal": "aosr_yoz",
      "rpc": "t2_aosr_yoz"
    },
    {
      "amal": "aosr_bekor",
      "rpc": "t2_aosr_bekor"
    },
    {
      "amal": "aosr_bog_saqla",
      "rpc": "t2_aosr_bog_saqla"
    },
    {
      "amal": "aosr_bog_ochir",
      "rpc": "t2_aosr_bog_ochir"
    },
    {
      "amal": "aosr_yoz_v2",
      "rpc": "t2_aosr_yoz_v2"
    },
    {
      "amal": "lab_protokol_yoz",
      "rpc": "t2_lab_protokol_yoz_v1"
    },
    {
      "amal": "lab_protokol_bekor",
      "rpc": "t2_lab_protokol_bekor_v1"
    },
    {
      "amal": "lab_protokol_bog_saqla",
      "rpc": "t2_lab_protokol_bog_saqla_v1"
    },
    {
      "amal": "kompaniya_logo_saqla",
      "rpc": "t2_kompaniya_logo_saqla_v1"
    },
    {
      "amal": "nakrutka_podval_saqla",
      "rpc": "t2_nakrutka_podval_saqla_v1"
    },
    {
      "amal": "nakrutka_podval_ochir",
      "rpc": "t2_nakrutka_podval_ochir_v1"
    },
    {
      "amal": "narx_manba_yoz",
      "rpc": "t2_narx_manba_yoz_v1"
    },
    {
      "amal": "narx_manba_bekor",
      "rpc": "t2_narx_manba_bekor_v1"
    },
    {
      "amal": "platforma_narx_manba_yoz",
      "rpc": "t2_platforma_narx_manba_yoz_v1"
    },
    {
      "amal": "platforma_narx_manba_bekor",
      "rpc": "t2_platforma_narx_manba_bekor_v1"
    },
    {
      "amal": "obyekt_hudud_belgila",
      "rpc": "t2_obyekt_hudud_belgila_v1"
    },
    {
      "amal": "narx_dalil_bogla",
      "rpc": "t2_narx_dalil_bogla_v1"
    },
    {
      "amal": "narx_dalil_ochir",
      "rpc": "t2_narx_dalil_ochir_v1"
    },
    {
      "amal": "audit_yoz",
      "rpc": "t2_audit_yoz"
    },
    {
      "amal": "hujjat_yoz",
      "rpc": "t2_obyekt_hujjat_yoz"
    },
    {
      "amal": "hujjat_ochir",
      "rpc": "t2_obyekt_hujjat_ochir"
    },
    {
      "amal": "sklad_mustaqil_yarat",
      "rpc": "t2_sklad_yarat"
    },
    {
      "amal": "kadr_mustaqil_yarat",
      "rpc": "t2_kadr_yarat"
    },
    {
      "amal": "texnika_mustaqil_yarat",
      "rpc": "t2_texnika_yarat"
    },
    {
      "amal": "resurs_yarat_v2",
      "rpc": "t2_resurs_yarat_v2"
    },
    {
      "amal": "resurs_yangila_v2",
      "rpc": "t2_resurs_yangila_v2"
    },
    {
      "amal": "resurs_bekor_v2",
      "rpc": "t2_resurs_bekor_v2"
    },
    {
      "amal": "resurs_bog_saqla",
      "rpc": "t2_resurs_bog_saqla"
    },
    {
      "amal": "resurs_bog_ochir",
      "rpc": "t2_resurs_bog_ochir"
    },
    {
      "amal": "loyiha_yarat",
      "rpc": "t2_loyiha_yarat"
    },
    {
      "amal": "loyiha_yangila",
      "rpc": "t2_loyiha_yangila"
    },
    {
      "amal": "loyiha_ochir",
      "rpc": "t2_loyiha_ochir"
    },
    {
      "amal": "obyekt_loyihaga_biriktir",
      "rpc": "t2_obyekt_loyihaga_biriktir"
    },
    {
      "amal": "obyekt_yarat",
      "rpc": "t2_obyekt_yarat_v1"
    },
    {
      "amal": "resurs_kategoriya_belgila",
      "rpc": "t2_resurs_kategoriya_belgila_v1"
    },
    {
      "amal": "nakrutka_koef_saqla",
      "rpc": "t2_nakrutka_koef_saqla_v1"
    },
    {
      "amal": "shartnoma_qamrov_saqla",
      "rpc": "t2_shartnoma_qamrov_saqla_v1"
    },
    {
      "amal": "loyiha_qatnashchi_biriktir",
      "rpc": "t2_loyiha_qatnashchi_biriktir"
    },
    {
      "amal": "loyiha_qatnashchi_ochir",
      "rpc": "t2_loyiha_qatnashchi_ochir"
    },
    {
      "amal": "kontragent_saqla",
      "rpc": "t2_kontragent_saqla"
    },
    {
      "amal": "kontragent_ochir",
      "rpc": "t2_kontragent_ochir"
    },
    {
      "amal": "fakt_yoz_v2",
      "rpc": "t2_fakt_yoz_v2"
    },
    {
      "amal": "fakt_belgila_v2",
      "rpc": "t2_fakt_belgila_v2"
    },
    {
      "amal": "fakt_belgila",
      "rpc": "t2_fakt_belgila"
    },
    {
      "amal": "azolik_qosh",
      "rpc": "t2_azolik_qosh_v1"
    },
    {
      "amal": "azolik_rol_ozgartir",
      "rpc": "t2_azolik_rol_ozgartir_v1"
    },
    {
      "amal": "azolik_ochir",
      "rpc": "t2_azolik_ochir_v1"
    },
    {
      "amal": "kompaniya_yangila",
      "rpc": "t2_kompaniya_yangila"
    },
    {
      "amal": "material_alias_yoz",
      "rpc": "t2_material_alias_yoz"
    },
    {
      "amal": "material_alias_ochir",
      "rpc": "t2_material_alias_ochir"
    },
    {
      "amal": "mindmap_bog",
      "rpc": "t2_mindmap_bog_v2"
    },
    {
      "amal": "mindmap_bog_ochir",
      "rpc": "t2_mindmap_bog_ochir_v2"
    },
    {
      "amal": "mindmap_joylashuv_saqla",
      "rpc": "t2_mindmap_joylashuv_saqla_v2"
    },
    {
      "amal": "mindmap_tugun_ochir",
      "rpc": "t2_mindmap_tugun_ochir_v2"
    }
  ]
} as const;
