import type { SaytSahifa } from './types';

/**
 * Foydalanuvchi sahifasining biznes ma'nosi. Route, o'qish oq ro'yxati va
 * yozish amallari generator orqali koddan olinadi; bu katalog esa PTO
 * xodimiga "bu sahifa nimaga xizmat qiladi" degan savolga javob beradi.
 */
export const SAHIFA_KATALOGI: readonly SaytSahifa[] = [
  { kalit: 'kompaniya', nom: 'Kompaniya va a’zolik', yol: '/admin/kompaniya', scope: 'GLOBAL', oqiydi: ['t2_men_v1', 't2_kompaniya'], yozadi: ['kompaniya_yangila', 'azolik_qosh', 'azolik_rol_ozgartir', 'azolik_ochir'], chiqaradi: ['Kompaniya profili', 'a’zolar va rollar'], beradi: ['/admin/dashboard', '/admin/loyiha'], izoh: 'Global kirish nuqtasi: kompaniya konteksti, a’zolar va ruxsatlar.' },
  { kalit: 'system-control', nom: 'Tizim boshqaruv markazi', yol: '/admin/system-control', scope: 'GLOBAL', oqiydi: ['t2_system_control_v1', 't2_capability_registry'], yozadi: ['tizim_amal', 'sozlama_saqla'], chiqaradi: ['sog‘liq va audit holati'], beradi: ['barcha modullar'], izoh: 'Global capability, health, incident va audit nazorati.' },
  { kalit: 'dashboard', nom: 'Rahbar paneli', yol: '/admin/dashboard', scope: 'COMPANY', oqiydi: ['t2_boss_dashboard_v1', 't2_bux_umumiy'], yozadi: [], chiqaradi: ['rahbar KPI va signallar'], beradi: ['/admin/loyiha', '/admin/hujjat-nazorat'], izoh: 'Tanlangan kompaniyaning bitta chegaralangan canonical read model ko‘rinishi.' },
  { kalit: 'loyiha', nom: 'Loyihalar', yol: '/admin/loyiha', scope: 'COMPANY', oqiydi: ['t2_loyiha_royxat', 't2_kompaniya'], yozadi: ['loyiha_yarat', 'loyiha_yangila', 'loyiha_ochir'], chiqaradi: ['loyiha ro‘yxati'], beradi: ['/admin/obyektlar', '/admin/participants'], izoh: 'Kompaniya ichidagi loyihalar va loyiha konteksi.' },
  { kalit: 'obyektlar', nom: 'Obyektlar ro‘yxati', yol: '/admin/obyektlar', scope: 'PROJECT', oqiydi: ['t2_obyekt', 't2_obyekt_jami'], yozadi: ['obyekt_yarat', 'obyekt_yangila', 'obyekt_loyihaga_biriktir'], chiqaradi: ['obyekt kartasi'], beradi: ['/admin/holat', '/admin/f2'], izoh: 'Loyiha ichidagi obyektning canonical ID va umumiy holati.' },
  { kalit: 'participants', nom: 'Loyiha ishtirokchilari', yol: '/admin/participants', scope: 'PROJECT', oqiydi: ['t2_loyiha_qatnashchilar_royxat'], yozadi: ['loyiha_qatnashchi_biriktir', 'loyiha_qatnashchi_ochir'], chiqaradi: ['ishtirokchilar ro‘yxati'], beradi: ['/admin/dashboard'], izoh: 'Buyurtmachi, pudratchi va boshqa loyiha tomonlari.' },
  { kalit: 'documents', nom: 'Hujjatlar', yol: '/admin/documents', scope: 'OBJECT', oqiydi: ['t2_obyekt_hujjat_royxat', 't2_document_registry'], yozadi: ['hujjat_yoz', 'hujjat_ochir'], chiqaradi: ['kanonik hujjat ro‘yxati'], beradi: ['/admin/hujjat-nazorat'], izoh: 'Obyekt hujjatlari va canonical fayl registri.' },
  { kalit: 'hujjat-nazorat', nom: 'Hujjat nazorati', yol: '/admin/hujjat-nazorat', scope: 'OBJECT', oqiydi: ['t2_document_registry', 't2_akt_reestr'], yozadi: [], chiqaradi: ['F2/Nakopitelniy completeness'], beradi: ['/admin/f2-tarix'], izoh: 'F2, Nakopitelniy va dalillar to‘liqligi.' },
  { kalit: 'f2-tarix', nom: 'F2 tarixi va tasdiqlash', yol: '/admin/f2-tarix', scope: 'OBJECT', oqiydi: ['t2_akt', 't2_akt_qator', 't2_akt_reestr'], yozadi: ['akt_tasdiqlash', 'akt_bekor', 'akt_correction_create_v1'], chiqaradi: ['tasdiqlangan F2 tarixi'], beradi: ['/admin/nakopitelniy', '/admin/f2-tayyorlash'], izoh: 'Tarixiy F2 manbasi va immutable tasdiqlash jarayoni.' },
  { kalit: 'mindmap', nom: 'Mindmap', yol: '/admin/mindmap', scope: 'COMPANY', oqiydi: ['t2_daraxt', 't2_mindmap_bog'], yozadi: ['mindmap_bog', 'mindmap_bog_ochir', 'mindmap_joylashuv_saqla', 'mindmap_tugun_ochir'], chiqaradi: ['graf ko‘rinishi'], beradi: ['/admin/loyiha'], izoh: 'Kompaniya va loyiha obyektlari o‘rtasidagi ko‘rinish.' },
  { kalit: 'crm', nom: 'Tashqi aloqa', yol: '/admin/crm', scope: 'COMPANY', oqiydi: ['t2_kontragent_royxat'], yozadi: ['kontragent_saqla', 'kontragent_ochir'], chiqaradi: ['kontragentlar'], beradi: ['/admin/participants', '/admin/shartnomalar'], izoh: 'Tashqi tashkilotlar va aloqa kartalari.' },
  { kalit: 'holat', nom: 'Smeta va Fakt / LRV', yol: '/admin/holat', scope: 'OBJECT', oqiydi: ['t2_daraxt', 't2_qator', 't2_qator_holat', 't2_akt'], yozadi: ['fakt_belgila_v2', 'fakt_yoz_v2'], chiqaradi: ['LRV va Fakt holati'], beradi: ['/admin/f2-tayyorlash', '/admin/nakopitelniy'], izoh: 'Smeta qatorlari, Fakt va F2 mumkin qoldig‘i.' },
  { kalit: 'f2', nom: 'F2 import', yol: '/admin/f2', scope: 'OBJECT', oqiydi: ['t2_daraxt', 't2_akt_reestr', 't2_qator_holat'], yozadi: ['f2_import_job_yarat', 'f2_import_draft_saqla', 'akt_yarat_v2'], chiqaradi: ['F2 import va bog‘lash natijasi'], beradi: ['/admin/f2-tarix', '/admin/nakopitelniy'], izoh: 'F2 faylini canonical smeta qatorlariga dalil bilan bog‘lash.' },
  { kalit: 'f2-tayyorlash', nom: 'F2 tayyorlash', yol: '/admin/f2-tayyorlash', scope: 'OBJECT', oqiydi: ['t2_daraxt', 't2_qator_holat', 't2_akt'], yozadi: ['akt_yarat_v2', 'akt_lifecycle_transition_v1'], chiqaradi: ['F2 qoralama va preapproval'], beradi: ['/admin/f2-tarix'], izoh: 'Fakt va tasdiqlangan F2 asosida keyingi davrni tayyorlash.' },
  { kalit: 'nakopitelniy', nom: 'Nakopitelniy vedomost', yol: '/admin/nakopitelniy', scope: 'OBJECT', oqiydi: ['t2_f2_kat_oy', 't2_akt', 't2_qator_holat'], yozadi: [], chiqaradi: ['oylik va jami Nakopitelniy'], beradi: ['/admin/m29', '/admin/f2-tarix'], izoh: 'Faqat tasdiqlangan F2 oylaridan yig‘ma ko‘rinish.' },
  { kalit: 'm29', nom: 'M-29', yol: '/admin/m29', scope: 'OBJECT', oqiydi: ['t2_f2_kat_oy', 't2_daraxt', 't2_qator_holat'], yozadi: [], chiqaradi: ['material norma va sarf'], beradi: ['/admin/nakopitelniy'], izoh: 'Materiallar bo‘yicha norma, sarf va oylar kesimi.' },
  { kalit: 'smeta-narxlash', nom: 'Smetani narxlash / RES', yol: '/admin/smeta-narxlash', scope: 'OBJECT', oqiydi: ['t2_daraxt', 't2_narx', 't2_material_alias_royxat'], yozadi: ['smeta_narxla_res', 'price_basis_yarat'], chiqaradi: ['narxlangan RES'], beradi: ['/admin/holat', '/admin/narxlar'], izoh: 'Smeta resurslari uchun narx manbasi va narxlash.' },
  { kalit: 'oferta', nom: 'Tender oferta', yol: '/admin/oferta', scope: 'OBJECT', oqiydi: ['t2_daraxt', 't2_narx'], yozadi: ['catalog_observation_yoz_v1'], chiqaradi: ['oferta va narx taklifi'], beradi: ['/admin/narxlar'], izoh: 'Individual smeta uchun narx takliflari.' },
  { kalit: 'narxlar', nom: 'Narxlar nazorati', yol: '/admin/narxlar', scope: 'COMPANY', oqiydi: ['t2_narx_markaz', 't2_narx_qol_xavf', 't2_narx_sana'], yozadi: ['narx_belgila', 'narx_sana_qosh'], chiqaradi: ['narx dalili va xavf'], beradi: ['/admin/smeta-narxlash', '/admin/oferta'], izoh: 'Narxning manbasi, sanasi va qo‘lda tuzatish izlari.' },
  { kalit: 'nakrutka', nom: 'Nakrutka hisobi', yol: '/admin/nakrutka', scope: 'OBJECT', oqiydi: ['t2_nakrutka', 't2_obyekt_nakrutka'], yozadi: ['nakrutka_saqla', 'nakrutka_koef_saqla'], chiqaradi: ['podval va ustama hisoblari'], beradi: ['/admin/nakopitelniy', '/admin/f2-tarix'], izoh: 'To‘g‘ri xarajatdan yakuniy qiymatgacha bo‘lgan kaskad.' },
  { kalit: 'moliya', nom: 'Moliya va shartnomalar', yol: '/admin/moliya', scope: 'COMPANY', oqiydi: ['t2_shartnoma', 't2_shartnoma_bog', 't2_bux_dashboard', 't2_tolov', 't2_xarajat'], yozadi: ['shartnoma_saqla', 'shartnoma_bog_saqla', 'tolov_yoz', 'xarajat_yoz'], chiqaradi: ['shartnoma va moliya holati'], beradi: ['/admin/dashboard', '/admin/hujjat-nazorat'], izoh: 'Loyiha/obyekt shartnomasi va moliyaviy oqim.' },
  { kalit: 'logistika', nom: 'Ta’minot va sklad', yol: '/admin/logistika', scope: 'COMPANY', oqiydi: ['t2_zayavka_royxat', 't2_sklad_qoldiq', 't2_sklad_harakat'], yozadi: ['erp_amal', 'skladga_yozish'], chiqaradi: ['ta’minot va sklad holati'], beradi: ['/admin/holat', '/admin/m29'], izoh: 'Smeta resurslaridan ta’minot va ombor jarayoniga o‘tish.' },
  { kalit: 'zayavka', nom: 'Zayavkalar', yol: '/admin/zayavka', scope: 'PROJECT', oqiydi: ['t2_zayavka_royxat'], yozadi: ['erp_amal'], chiqaradi: ['material va xizmat so‘rovi'], beradi: ['/admin/logistika'], izoh: 'Loyiha ehtiyojlari bo‘yicha so‘rovlar.' },
  { kalit: 'aosr', nom: 'QA/QC — AOSR', yol: '/admin/aosr', scope: 'OBJECT', oqiydi: ['t2_aosr_reestr_v2', 't2_lab_protokol_reestr'], yozadi: ['aosr_yoz_v2', 'lab_protokol_yoz'], chiqaradi: ['AOSR va laboratoriya hujjatlari'], beradi: ['/admin/hujjat-nazorat'], izoh: 'Ijro hujjatlari va laboratoriya dalillari.' },
  { kalit: 'erp', nom: 'Kadrlar va texnika', yol: '/admin/erp', scope: 'COMPANY', oqiydi: ['v_erp_kadrlar_dashboard', 'v_erp_texnika_dashboard', 'v_erp_taminot_dashboard'], yozadi: ['erp_amal'], chiqaradi: ['ERP umumiy ko‘rinishi'], beradi: ['/admin/dashboard'], izoh: 'Qurilish kompaniyasining yordamchi operatsion modullari.' },
  { kalit: 'sozlamalar', nom: 'Sozlamalar', yol: '/admin/tizim-sozlama', scope: 'COMPANY', oqiydi: ['t2_sozlama', 't2_resurs_kategoriya'], yozadi: ['sozlama_saqla', 'resurs_kategoriya_belgila'], chiqaradi: ['kompaniya sozlamalari'], beradi: ['barcha hisoblar'], izoh: 'Koeffitsient, kategoriya va tizim sozlamalari.' },
  { kalit: 'storage', nom: 'Fayl saqlash', yol: '/admin/storage', scope: 'COMPANY', oqiydi: ['t2_papka_daraxt', 't2_obyekt_hujjat_royxat'], yozadi: [], chiqaradi: ['kanonik/private fayl holati'], beradi: ['/admin/documents'], izoh: 'R2 canonical fayl truth va secondary replica holati.' },
  { kalit: 'fayl-boglash', nom: 'Fayl bog‘lash va sinxronizatsiya', yol: '/admin/fayl-boglash', scope: 'COMPANY', oqiydi: ['t2_manba', 't2_obyekt_hujjat_royxat'], yozadi: [], chiqaradi: ['fayl lineage va replica holati'], beradi: ['/admin/documents'], izoh: 'Hujjatning manba va replica bog‘lanishi.' },
  { kalit: 'korzinka', nom: 'Korzinka', yol: '/admin/korzinka', scope: 'COMPANY', oqiydi: ['t2_korzinka'], yozadi: ['korzinkaga_tashlash', 'korzinkadan_tiklash'], chiqaradi: ['bekor qilingan yozuvlar'], beradi: ['tegishli modul'], izoh: 'Qayta tiklanadigan bekor qilingan obyektlar va harakatlar.', legacy: true },
  { kalit: 'buxgalteriya', nom: 'Buxgalteriya', yol: '/admin/buxgalteriya', scope: 'COMPANY', oqiydi: ['t2_bux_dashboard', 't2_tolov', 't2_xarajat'], yozadi: ['tolov_yoz', 'xarajat_yoz'], chiqaradi: ['buxgalteriya ko‘rinishi'], beradi: ['/admin/moliya'], izoh: 'Tarixiy kirish yo‘li; asosiy moliya oqimi /admin/moliya ichida.', legacy: true },
  { kalit: 'ierarxiya', nom: 'Ierarxiya', yol: '/admin/ierarxiya', scope: 'COMPANY', oqiydi: ['t2_daraxt'], yozadi: [], chiqaradi: ['smeta daraxti'], beradi: ['/admin/holat'], izoh: 'Tarixiy texnik ko‘rinish; kundalik ish uchun Smeta va Fakt sahifasi ishlatiladi.', legacy: true },
  { kalit: 'monitoring', nom: 'Monitoring', yol: '/admin/monitoring', scope: 'GLOBAL', oqiydi: ['t2_hodisa_lenta', 't2_audit_reestr'], yozadi: [], chiqaradi: ['texnik monitoring'], beradi: ['/admin/system-control'], izoh: 'Tarixiy texnik monitoring sahifasi.', legacy: true },
  { kalit: 'shaxsiy-smeta', nom: 'Shaxsiy smeta', yol: '/admin/shaxsiy-smeta', scope: 'COMPANY', oqiydi: ['t2_shaxsiy_smeta'], yozadi: ['shaxsiy_smeta_yarat'], chiqaradi: ['shaxsiy smeta'], beradi: ['/admin/loyiha'], izoh: 'Tarixiy smeta kalkulyatori va alohida yo‘l.', legacy: true },
  { kalit: 'supabase', nom: 'Supabase sozlamasi', yol: '/admin/supabase', scope: 'GLOBAL', oqiydi: ['t2_sozlama'], yozadi: ['sozlama_saqla'], chiqaradi: ['integratsiya sozlamasi'], beradi: ['/admin/system-control'], izoh: 'Texnik sozlama sahifasi; kundalik PTO oqimining qismi emas.', legacy: true },
  { kalit: 'tezlik', nom: 'Tezlik sinovi', yol: '/admin/tezlik', scope: 'GLOBAL', oqiydi: [], yozadi: [], chiqaradi: ['performance probe'], beradi: [], izoh: 'Texnik diagnostika sahifasi.', legacy: true },
  { kalit: 'site-map', nom: 'Sayt xaritasi', yol: '/admin/sayt-xaritasi', scope: 'GLOBAL', oqiydi: ['koddan yig‘ilgan manifest'], yozadi: [], chiqaradi: ['TIZIM_02 oqim xaritasi'], beradi: ['barcha modullar'], izoh: 'Sahifa, canonical read/write va hujjat oqimining bitta ko‘rinishi.' },
  { kalit: 'ai-agentlar', nom: 'AI ishchilar (agentlar)', yol: '/admin/ai-agentlar', scope: 'COMPANY', oqiydi: ['t2_agent_control_v1'], yozadi: ['agent run_transition', 'agent approval_decide'], chiqaradi: ['agent run va tasdiq jurnali'], beradi: ['kanonik buyruqlar (faqat tasdiq bilan)'], izoh: 'Chegaralangan agent rollari, inson tasdig‘i va audit — AI ishchilar poydevori.' },
];

export const SAHIFA_KATALOGI_BY_PATH = new Map(SAHIFA_KATALOGI.map((x) => [x.yol, x]));
