import { calculateProgressValuation, money } from './calculation'; import type { CloseoutReportRow, ConstructionDocumentControlReadModel, WorkbenchException } from './types';
const bad = (s:string) => ['missing','rejected','superseded','unresolved'].includes(s);
export function validateProjectCloseout(model: Pick<ConstructionDocumentControlReadModel,'objectId'|'requirements'|'documents'>):CloseoutReportRow[]{return model.requirements.map(req=>{if(req.rule==='payment_rule_unresolved')return{objectId:model.objectId,requirement:req.requirementId,status:'unresolved',blocking:req.required,evidenceIds:[],reason:'FORMA3_RULE_UNRESOLVED'};const all=model.documents.filter(d=>d.type===req.type&&(!req.periodId||d.periodId===req.periodId));const usable=all.find(d=>req.requiresApproved?d.status==='approved':['approved','present','pending'].includes(d.status));if(usable)return{objectId:model.objectId,requirement:req.requirementId,status:usable.status,blocking:false,evidenceIds:[usable.documentId,...(usable.evidenceIds??[])],reason:usable.status==='approved'?'Approved evidence present.':'Evidence awaiting approval.'};const reject=all.find(d=>d.status==='rejected'), superceded=all.find(d=>d.status==='superseded'), status=reject?'rejected':superceded?'superseded':req.required?'missing':'required';return{objectId:model.objectId,requirement:req.requirementId,status,blocking:req.required&&bad(status),evidenceIds:reject?[reject.documentId]:superceded?[superceded.documentId]:[],reason:reject?'Evidence rejected.':superceded?'Only superseded evidence exists.':req.required?'Required evidence missing.':'Optional requirement.'};});}
export function exportExceptions(model:ConstructionDocumentControlReadModel):WorkbenchException[]{const r=[] as WorkbenchException[];const valuation=calculateProgressValuation(model.valuation);for(const row of valuation.rows){for(const code of row.warnings){const blocking=code==='OVER_CERTIFICATION'||code==='MISSING_CERTIFIED_AMOUNT'||code==='MISSING_BASELINE_PRICE'||code==='MISSING_BASELINE_QUANTITY';r.push({code,severity:blocking?'error':'warning',entityId:row.lineId,objectId:model.objectId,periodId:model.currentPeriodId,reason:code.replaceAll('_',' ').toLowerCase(),blocking,suggestedAction:code==='OVER_CERTIFICATION'?'Reconcile certified quantity with approved entitlement.':code==='MISSING_CERTIFIED_AMOUNT'?'Restore the exact amount from the approved F2 source document; do not substitute quantity × price.':code==='MISSING_BASELINE_PRICE'?'Attach or resolve the authoritative baseline/reference price.':code==='MISSING_BASELINE_QUANTITY'?'Attach or resolve the authoritative baseline quantity.':'Supply canonical evidence or resolve change.'});}}for(const x of validateProjectCloseout(model))if(x.blocking)r.push({code:x.status==='superseded'?'DOCUMENT_SUPERSEDED':'DOCUMENT_MISSING',severity:'error',entityId:x.requirement,objectId:model.objectId,periodId:model.currentPeriodId,reason:x.reason,blocking:true,suggestedAction:'Attach or approve the required canonical document.'});return r;}
/** Deterministic export preview: calculation source and export source are the same result. */
function cyrb53(str: string, seed = 0) {
  let h1 = 0xdeadbeef ^ seed, h2 = 0x41c6ce57 ^ seed;
  for (let i = 0, ch; i < str.length; i++) {
    ch = str.charCodeAt(i);
    h1 = Math.imul(h1 ^ ch, 2654435761);
    h2 = Math.imul(h2 ^ ch, 1597334677);
  }
  h1 = Math.imul(h1 ^ (h1 >>> 16), 2246822507) ^ Math.imul(h2 ^ (h2 >>> 13), 3266489909);
  h2 = Math.imul(h2 ^ (h2 >>> 16), 2246822507) ^ Math.imul(h1 ^ (h1 >>> 13), 3266489909);
  return 4294967296 * (2097151 & h2) + (h1 >>> 0);
}

export function createExportPreview(model:ConstructionDocumentControlReadModel){const result=calculateProgressValuation(model.valuation);const reconciliation=result.rows.flatMap(row=>{const errors:{lineId:string;code:string}[]=[];if(money(row.previousQuantity+row.currentQuantity)!==money(row.cumulativeQuantity))errors.push({lineId:row.lineId,code:'NAKOPITELNIY_MISMATCH'});if(row.previousValue===null||row.currentValue===null||row.cumulativeValue===null)errors.push({lineId:row.lineId,code:'MISSING_BASELINE_PRICE'});else if(money(row.previousValue+row.currentValue)!==money(row.cumulativeValue))errors.push({lineId:row.lineId,code:'NAKOPITELNIY_MISMATCH'});if(row.previousCertifiedValue===null||row.currentCertifiedValue===null||row.cumulativeCertifiedValue===null)errors.push({lineId:row.lineId,code:'MISSING_CERTIFIED_AMOUNT'});else if(money(row.previousCertifiedValue+row.currentCertifiedValue)!==money(row.cumulativeCertifiedValue))errors.push({lineId:row.lineId,code:'NAKOPITELNIY_MISMATCH'});return errors;});const officialRows=result.rows.map(row=>({description:row.description,unit:row.unit,baselineQuantity:row.baselineQuantity,baselineReferencePrice:row.baselineReferencePrice,approvedChangeQuantity:row.approvedChangeQuantity,approvedEntitlementQuantity:row.approvedEntitlementQuantity,previousQuantity:row.previousQuantity,currentQuantity:row.currentQuantity,cumulativeQuantity:row.cumulativeQuantity,remainingQuantity:row.remainingQuantity,currentF2ValuationPrice:row.currentF2ValuationPrice,currentCertifiedValue:row.currentCertifiedValue,previousCertifiedValue:row.previousCertifiedValue,cumulativeCertifiedValue:row.cumulativeCertifiedValue}));
const projectionHash = cyrb53(JSON.stringify(officialRows)).toString(16);
return{f2PeriodId:model.valuation.periods[model.valuation.throughPeriod].periodId,estimateRevisionId:model.valuation.estimateRevisionId,rows:result.rows,officialRows,totals:result.totals,reconciliation,documents:model.valuation.periods[model.valuation.throughPeriod].documentIds, projectName: model.projectName, objectName: model.objectName, contractId: model.contractId, projectionHash};}
export function closeoutJson(model:ConstructionDocumentControlReadModel){return JSON.stringify({report:validateProjectCloseout(model),export:createExportPreview(model)},null,2);}
