/** Public copy, not a runtime entitlement or readiness registry. Evidence: pageCatalog/App routes. */
export type EntryCopy = readonly [uz: string, ru: string, en: string];
export const scopeCopy = {
  eyebrow: ['QURILISH KOMPANIYASI UCHUN YAGONA ISH MUHITI', 'ЕДИНАЯ РАБОЧАЯ СРЕДА СТРОИТЕЛЬНОЙ КОМПАНИИ', 'ONE WORKSPACE FOR YOUR CONSTRUCTION COMPANY'],
  title: ['Qurilishni boshqaring.', 'Управляйте строительством.', 'Manage construction.'],
  accent: ['Faqat hujjatlarni emas.', 'Не только документами.', 'Not just documents.'],
  description: ['Loyiha, shartnoma, smeta, resurslar va bajarilgan ishlarni bir joyda boshqaring. Rahbar, PTO muhandisi, smetachi va ta’minot xodimi bitta loyihada o‘z vazifasini bajaradi, ma’lumotlar esa bir-biriga bog‘langan holda yuritiladi.', 'От проекта и договора до сметы, ресурсов, выполненных работ и расчётов. Руководитель, ПТО, сметчик и снабжение работают над одним проектом — каждый в своей роли.', 'From projects and contracts to estimates, resources, progress and settlement. Bring management, engineering, estimating and procurement together around the same project.'],
  map: ['Tizimning ish xaritasi', 'Карта рабочих процессов', 'Your connected workspace'],
  mapNote: ['Yo‘nalishni bosing — u qaysi vazifaga xizmat qilishini ko‘ring.', 'Выберите направление и узнайте, какие задачи оно решает.', 'Choose a workflow to explore the tasks it supports.'],
  foundation: ['Kompaniya → Loyiha → Obyekt', 'Компания → Проект → Объект', 'Company → Project → Object'],
  modules: ['Bir kompaniya. Bog‘langan ish yo‘nalishlari.', 'Одна компания. Связанные направления работы.', 'One company. Connected workflows.'],
  modulesNote: ['Quyidagi modullar tizimda mavjud. Aniq imkoniyatlar rol va modul holatiga bog‘liq; rivojlanayotgan qismlar alohida ko‘rsatilgan.', 'Ниже представлены модули системы. Возможности зависят от роли и состояния модуля; развивающиеся части отмечены отдельно.', 'These modules exist in the system. Availability depends on your role and module status; evolving areas are marked separately.'],
  roles: ['Tizim sizning ishingizni qanday yengillashtiradi?', 'Что изменится в вашей работе?', 'What changes for your role?'],
  audiences: ['Jamoa uchun', 'Для команды', 'For your team'],
  rolesNote: ['Lavozimingizni tanlab, kundalik vazifalar va tayyorlanadigan hujjatlar bilan tanishing.', 'Выберите роль: ежедневные задачи, проверяемые данные и результат.', 'Choose a role to explore your daily workflow, evidence and outputs.'],
  workflow: ['Bitta obyekt bo‘yicha to‘liq ish zanjiri.', 'Полная цепочка работы по одному объекту.', 'Follow one object through the full workflow.'],
  workflowNote: ['Excel fayllarini alohida-alohida yuritish o‘rniga, har bosqichdagi manbani va keyingi hujjatga bog‘lanishni kuzating.', 'Вместо разрозненных Excel-файлов отслеживайте источник каждого этапа и его связь со следующим документом.', 'Instead of disconnected spreadsheets, follow each stage’s source and its connection to the next document.'],
  trust: ['Har bir hisobning manbasini tekshiring.', 'Проверяйте расчёт. Видите источник.', 'Trace the calculation back to its source.'],
  account: ['Tizimga qo‘shiling yoki ishni davom ettiring.', 'Присоединяйтесь или продолжайте работу.', 'Join your team or continue your work.'],
  accountNote: ['Ro‘yxatdan o‘ting va kompaniyangizga kirish ruxsatini olgach, loyiha hamda obyektlaringiz bilan ishlang. Hisobingiz bo‘lsa, tizimga kiring.', 'Создайте аккаунт, получите доступ к компании и работайте в контексте проекта и объекта. Уже есть аккаунт — войдите.', 'Create an account, obtain company access and work within a project and object. Already registered? Sign in.'],
  developing: ['Rivojlanayotgan imkoniyatlar', 'Развивающиеся возможности', 'Evolving capabilities'],
  result: ['Ish natijasi', 'Результат работы', 'Your output'],
} satisfies Record<string, EntryCopy>;

export const productDomains: readonly { id: string; title: EntryCopy; detail: EntryCopy; items: EntryCopy; note?: EntryCopy }[] = [
  { id: 'projects', title: ['Kompaniya va loyihalar', 'Компания и проекты', 'Company & projects'], detail: ['Kim, qaysi loyiha va qaysi obyekt ustida ishlayapti — aniq kontekst.', 'Кто работает, над каким проектом и объектом — понятный контекст.', 'Keep the actor, company, project and object clear.'], items: ['Kompaniyalar · loyihalar · obyektlar · ishtirokchilar · shartnomalar · rollar', 'Компании · проекты · объекты · участники · договоры · роли', 'Companies · projects · objects · participants · contracts · roles'] },
  { id: 'estimate', title: ['Smeta va normativlar', 'Смета и нормативы', 'Estimates & norms'], detail: ['Excel smetani o‘qing yoki katalogdan ish va resurslarni tanlab smeta yig‘ing.', 'Импортируйте Excel или собирайте смету из работ и ресурсов каталога.', 'Import an Excel estimate or assemble work and resources from the catalogue.'], items: ['LRV/RES import · smeta studiyasi · bo‘lim/ish/resurs daraxti · koeffitsientlar', 'Импорт ЛРВ/РЕС · сметная студия · дерево разделов/работ/ресурсов · коэффициенты', 'LRV/RES import · estimate studio · section/work/resource tree · coefficients'], note: ['Smeta studiyasi va koeffitsient tavsiyalari takomillashtirilmoqda.', 'Студия и рекомендации коэффициентов дорабатываются.', 'Studio and coefficient recommendations are being refined.'] },
  { id: 'progress', title: ['Fakt, F2 va davrlar', 'Факт, Ф2 и периоды', 'Progress, F2 & periods'], detail: ['Bajarilgan hajmdan F2ga olish mumkin bo‘lgan hajmgacha; manba bilan yonma-yon tekshirish.', 'От факта до доступного объёма Ф2; проверка рядом с источником.', 'From completed quantities to F2 eligibility, with side-by-side source review.'], items: ['Fakt · Ostatka · F2 tayyorlash/import · tarix · Nakopitelniy · F3', 'Факт · остаток · подготовка/импорт Ф2 · история · накопительная · Ф3', 'Progress · remaining scope · F2 preparation/import · history · cumulative · F3'] },
  { id: 'pricing', title: ['Narxlar va oferta', 'Цены и оферта', 'Pricing & offers'], detail: ['Narxni faqat raqam emas, sana, manba va dalil bilan ko‘ring.', 'Цена — не только число: дата, источник и обоснование.', 'A price with its date, source and evidence, not just a number.'], items: ['Katalog · chel-chas/mash-chas · narx dalili · narx nazorati · oferta · ustamalar', 'Каталог · чел-ч/маш-ч · обоснование · контроль цен · оферта · начисления', 'Catalogues · labour/machine hours · evidence · price control · offers · markups'] },
  { id: 'supply', title: ['Ta’minot va sklad', 'Снабжение и склад', 'Procurement & warehouse'], detail: ['Obyekt ehtiyoji, material talabi va ombor harakatlarini bir ish yo‘nalishida ko‘ring.', 'Потребность объекта, заявки и движение склада в одном направлении.', 'Review object demand, material requests and warehouse movements together.'], items: ['Zayavka · viborka · logistika · ombor · resurs vedomosti · M-29', 'Заявки · выборка · логистика · склад · ведомость ресурсов · М-29', 'Requests · take-off · logistics · warehouse · resource statement · M-29'] },
  { id: 'documents', title: ['Ijro va hujjat nazorati', 'Исполнительная документация', 'Execution & document control'], detail: ['Ishni hujjat, imzo, dalil va tasdiqlash tarixi bilan kuzating.', 'Связывайте работы с документами, подписями, доказательствами и историей согласования.', 'Trace work through documents, signatories, evidence and approval history.'], items: ['АОСР · laboratoriya · hujjat reestri · Excel eksport · topshirish/tasdiqlash', 'АОСР · лаборатория · реестр · экспорт Excel · передача/согласование', 'Hidden-work acts · laboratory · registry · Excel exports · submission/approval'] },
  { id: 'finance', title: ['Shartnoma va hisob-kitob', 'Договоры и расчёты', 'Contracts & settlement'], detail: ['Shartnoma, akt va to‘lov ma’lumotlarini loyiha/obyekt kontekstida ko‘ring.', 'Просматривайте договоры, акты и платежи в контексте проекта и объекта.', 'Review contract, certificate and payment data within the project/object context.'], items: ['Shartnoma liniyasi · moliya · to‘lovlar · buyurtmachi kabineti · taqdimlar', 'Линия договора · финансы · платежи · кабинет заказчика · представления', 'Contract lineage · finance · payments · client workspace · submissions'], note: ['To‘liq buxgalteriya yoki soliq hisobotining o‘rnini bosishi da’vo qilinmaydi.', 'Не заявляется замена полной бухгалтерии и налоговой отчётности.', 'Not advertised as a complete accounting or tax reporting replacement.'] },
  { id: 'agents', title: ['AI ishchilar va boshqaruv', 'AI-сотрудники и управление', 'AI workers & control'], detail: ['Savol, izlash va tahlilga yordam; harakatlar rol, ruxsat va tasdiq bilan chegaralanadi.', 'Помощь с вопросами, поиском и анализом; действия ограничены ролью, доступом и подтверждением.', 'Help with questions, search and analysis; actions are bounded by role, permission and approval.'], items: ['Jarvis · lavozimli agentlar · xarajat nazorati · tasdiq jurnali · tizim xaritasi', 'Jarvis · роли агентов · контроль затрат · журнал подтверждений · карта системы', 'Jarvis · role-based agents · cost control · approval log · system map'], note: ['AI narx yoki normani o‘ylab topmaydi; avtomatik yakuniy tasdiq va’da qilinmaydi.', 'AI не выдумывает цены и нормы; автоматическое финальное согласование не обещается.', 'AI must not invent prices or norms; automatic final approval is not promised.'] },
];

export const productRoles: readonly { id: string; title: EntryCopy; task: EntryCopy; result: EntryCopy }[] = [
  { id: 'director', title: ['Rahbar', 'Руководитель', 'Management'], task: ['Loyihalar holati, bajarilgan ish, tasdiqlangan akt va muammoli hujjatlarni kuzating. Kompaniya va obyekt kontekstini almashtirib ko‘ring.', 'Контролируйте проекты, выполненные работы, утверждённые акты и проблемные документы. Переключайтесь между компанией и объектами.', 'Review projects, progress, approved certificates and document issues across company and object contexts.'], result: ['Rahbar paneli · obyektlar holati · hujjatlar tarixi', 'Панель руководителя · состояние объектов · история документов', 'Management dashboard · object status · document history'] },
  { id: 'pto', title: ['PTO muhandisi', 'Инженер ПТО', 'Project engineer'], task: ['Faktni kiriting, F2 qatorlarini smeta bilan solishtiring, bog‘lanish va summadagi farqlarni tekshiring. Davr hujjatlarini tayyorlang.', 'Вносите факт, сверяйте Ф2 со сметой, проверяйте связи и расхождения сумм. Готовьте документы периода.', 'Record progress, reconcile F2 against estimates and review line/amount differences. Prepare period documents.'], result: ['F2 · Nakopitelniy · F3 · АОСР · resurs vedomosti', 'Ф2 · накопительная · Ф3 · АОСР · ведомость ресурсов', 'F2 · cumulative statement · F3 · hidden-work acts · resource statement'] },
  { id: 'estimator', title: ['Smetachi', 'Сметчик', 'Estimator'], task: ['LRV/RES fayllarni tahlil qiling, katalogdan ish toping, bo‘lim va resurslar bo‘yicha smetani yig‘ing. Narx manbasini ko‘rib, ofertani asoslang.', 'Анализируйте ЛРВ/РЕС, находите работы в каталоге, собирайте разделы и ресурсы. Проверяйте источник цен для обоснования оферты.', 'Analyse LRV/RES, find catalogue work and assemble sections/resources. Review price evidence for an offer.'], result: ['Smeta qoralamasi · narx dalili · oferta', 'Черновик сметы · обоснование цен · оферта', 'Estimate draft · price evidence · offer'] },
  { id: 'supply', title: ['Ta’minot / sklad', 'Снабжение / склад', 'Procurement / warehouse'], task: ['Obyektga zarur materialni ko‘ring, talabnoma va ombor ma’lumotlarini yuriting, resurs sarfini hujjat bilan solishtiring.', 'Просматривайте потребность объекта, ведите заявки и складские данные, сверяйте расход с документами.', 'Review object material demand, manage requests/warehouse data and reconcile consumption against documents.'], result: ['Zayavka · viborka · sklad · M-29', 'Заявка · выборка · склад · М-29', 'Requests · take-off · warehouse · M-29'] },
  { id: 'finance', title: ['Moliya xodimi', 'Финансовый специалист', 'Finance'], task: ['Qaysi shartnoma va obyektga qaysi akt/to‘lov tegishli ekanini kuzating. Hisoblarni hujjat manbasi bilan ko‘ring.', 'Отслеживайте принадлежность актов и платежей договору и объекту. Проверяйте расчёты по документам.', 'Trace certificates and payments to their contract/object and review calculations with document evidence.'], result: ['Shartnoma · aktlar · to‘lov tarixi', 'Договор · акты · история платежей', 'Contracts · certificates · payment history'] },
  { id: 'client', title: ['Buyurtmachi', 'Заказчик', 'Client'], task: ['Sizga ochilgan obyekt va taqdim etilgan hujjatlarni ko‘ring. Izoh, qabul, rad yoki tuzatish so‘rovini bir jarayonda yuriting.', 'Просматривайте открытые вам объекты и представленные документы. Ведите замечания, приёмку, отказ и запрос исправлений.', 'Review shared objects and submitted documents, with comments, acceptance, rejection and correction requests.'], result: ['Buyurtmachi kabineti · taqdimlar · qaror tarixi', 'Кабинет заказчика · представления · история решений', 'Client workspace · submissions · decision history'] },
];

export const chainSteps: readonly EntryCopy[] = [
  ['Loyiha va shartnoma', 'Проект и договор', 'Project & contract'],
  ['Smeta va narx manbasi', 'Смета и источник цен', 'Estimate & price source'],
  ['Resurs va bajarilgan ish', 'Ресурсы и выполненные работы', 'Resources & progress'],
  ['F2 va tasdiqlangan tarix', 'Ф2 и утверждённая история', 'F2 & approved history'],
  ['Nakopitelniy, F3 va topshirish', 'Накопительная, Ф3 и передача', 'Cumulative, F3 & submission'],
];
export const trustPoints: readonly EntryCopy[] = [
  ['Smeta narxi, F2 narxi va haqiqiy xarid narxi — alohida qiymatlar.', 'Сметная цена, цена Ф2 и фактическая закупочная цена — разные значения.', 'Estimate, certified F2 and procurement prices are distinct facts.'],
  ['Tasdiqlangan F2 tarixini yangi smeta narxi bilan qayta hisoblamaslik.', 'Не пересчитывать утверждённую историю Ф2 по новой сметной цене.', 'Do not revalue approved historical F2 with a new estimate price.'],
  ['Noma’lum qiymatni yashirincha nolga aylantirmaslik; yetishmayotgan dalilni ko‘rsatish.', 'Не превращать неизвестное в ноль; показывать отсутствующее обоснование.', 'Do not silently turn unknown into zero; show missing evidence.'],
  ['Kompaniya ruxsatlari, hujjat manbasi va tasdiqlash tarixi saqlanadigan ish tartibi.', 'Права компании, источник документа и история согласования в рабочем процессе.', 'A workflow with company access, document provenance and approval history.'],
];
