-- T2-AGENT-CONTROL-PLANE-001
-- Source-only additive contract for bounded construction agents.
--
-- This is not an AI truth table. It records agent identity, guarded runs,
-- approval decisions and tool-call receipts. Business calculations remain in
-- the canonical domain commands/RPCs owned by their respective modules.

begin;

create table if not exists public.t2_agent_profile (
  kod text primary key,
  nom text not null,
  rol text not null,
  izoh text,
  permission_mode text not null default 'read_only'
    check (permission_mode in ('read_only','analyze','draft','command_prepare','human_approval_required')),
  allowed_commands jsonb not null default '[]'::jsonb
    check (jsonb_typeof(allowed_commands) = 'array'),
  allowed_tools jsonb not null default '[]'::jsonb
    check (jsonb_typeof(allowed_tools) = 'array'),
  default_scope text not null default 'company'
    check (default_scope in ('global','company','project','object')),
  holat text not null default 'active'
    check (holat in ('active','paused','deprecated')),
  versiya integer not null default 1 check (versiya > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.t2_agent_run (
  id bigint generated by default as identity primary key,
  operation_id uuid not null unique,
  agent_kod text not null references public.t2_agent_profile(kod),
  actor_id bigint not null references public.t2_foydalanuvchi(id),
  kompaniya_id bigint references public.t2_kompaniya(id),
  loyiha_id bigint references public.t2_loyiha(id),
  obyekt_id bigint references public.t2_obyekt(id),
  command_kod text not null,
  holat text not null default 'queued'
    check (holat in ('queued','running','waiting_review','approval_required','applying','exporting','completed','failed','cancelled')),
  requires_approval boolean not null default true,
  input jsonb not null default '{}'::jsonb,
  result jsonb,
  error_code text,
  error_detail text,
  versiya integer not null default 1 check (versiya > 0),
  created_at timestamptz not null default now(),
  started_at timestamptz,
  finished_at timestamptz,
  updated_at timestamptz not null default now()
);

create index if not exists t2_agent_run_scope_ix
  on public.t2_agent_run (kompaniya_id, loyiha_id, obyekt_id, created_at desc);
create index if not exists t2_agent_run_state_ix
  on public.t2_agent_run (holat, updated_at desc);

create table if not exists public.t2_agent_approval (
  id bigint generated by default as identity primary key,
  run_id bigint not null unique references public.t2_agent_run(id) on delete cascade,
  holat text not null default 'pending'
    check (holat in ('pending','approved','rejected')),
  requested_at timestamptz not null default now(),
  decided_at timestamptz,
  decided_by bigint references public.t2_foydalanuvchi(id),
  sabab text,
  versiya integer not null default 1 check (versiya > 0)
);

create table if not exists public.t2_agent_tool_call (
  id bigint generated by default as identity primary key,
  run_id bigint not null references public.t2_agent_run(id) on delete cascade,
  sequence_no integer not null check (sequence_no > 0),
  operation_id uuid not null unique,
  actor_id bigint not null references public.t2_foydalanuvchi(id),
  tool_kod text not null,
  holat text not null default 'prepared'
    check (holat in ('prepared','executed','failed','blocked')),
  request jsonb not null default '{}'::jsonb,
  result jsonb,
  error_code text,
  created_at timestamptz not null default now(),
  unique (run_id, sequence_no)
);

create index if not exists t2_agent_tool_call_run_ix
  on public.t2_agent_tool_call (run_id, sequence_no);

create table if not exists public.t2_agent_command_log (
  operation_id uuid primary key,
  actor_id bigint not null references public.t2_foydalanuvchi(id),
  command text not null,
  natija jsonb not null,
  created_at timestamptz not null default now()
);

-- Initial role catalog. Tools are capability codes, not arbitrary SQL/function
-- names. A tool call only creates an auditable prepared receipt; it never
-- executes an unregistered command.
insert into public.t2_agent_profile (kod, nom, rol, izoh, permission_mode, allowed_commands, allowed_tools, default_scope)
values
 ('platform_orchestrator','Platform Orchestrator','orchestrator','Global health, routing and approval orchestration','human_approval_required','["system.health.read","job.inspect","command.prepare","approval.request"]','["system.health.read","job.inspect","command.prepare","approval.request"]','global'),
 ('company_access','Company & Access','company_access','Company context, membership and permission analysis','command_prepare','["company.context.read","membership.read","permission.analyze"]','["company.read","membership.read","permission.analyze","command.prepare"]','company'),
 ('project_contract','Project & Contract','project_contract','Project, object and contract lineage analysis','command_prepare','["project.lineage.read","contract.read"]','["project.read","object.read","contract.read","lineage.analyze","command.prepare"]','project'),
 ('pto_smeta','PTO/Smeta','pto','Canonical estimate, Fakt, F2 and cumulative analysis','human_approval_required','["f2.draft.prepare","f2.export.prepare"]','["smeta.read","fakt.read","f2.read","nakopitelniy.read","document.read","command.prepare"]','object'),
 ('document_control','Document Control','document_control','Evidence, registry and closeout analysis','command_prepare','["document.closeout.prepare"]','["document.read","document.lineage.read","closeout.read","replica.status.read","command.prepare"]','object'),
 ('procurement','Procurement','procurement','Material need, RFQ and award analysis','human_approval_required','["procurement.award.prepare"]','["procurement.read","price.read","supplier.read","command.prepare"]','project'),
 ('warehouse','Warehouse','warehouse','Receipt and stock movement analysis','human_approval_required','["warehouse.receipt.prepare"]','["warehouse.read","receipt.read","movement.read","command.prepare"]','project'),
 ('finance','Accounting/Finance','finance','Contract, cost and payment read model analysis','human_approval_required','["finance.payment.prepare"]','["finance.read","contract.read","payment.read","command.prepare"]','company'),
 ('schedule_execution','Schedule/Execution','schedule','Schedule, progress and delay analysis','command_prepare','["schedule.risk.prepare"]','["schedule.read","progress.read","risk.analyze","command.prepare"]','project'),
 ('quality_handover','Quality/Handover','quality','Quality, AOSR and handover completeness analysis','command_prepare','["quality.handover.prepare"]','["quality.read","aosr.read","handover.read","closeout.read","command.prepare"]','object')
on conflict (kod) do update set
  nom = excluded.nom,
  rol = excluded.rol,
  izoh = excluded.izoh,
  permission_mode = excluded.permission_mode,
  allowed_commands = excluded.allowed_commands,
  allowed_tools = excluded.allowed_tools,
  default_scope = excluded.default_scope,
  updated_at = now();

create or replace function public.t2_agent_scope_guard_v1(
  p_actor_id bigint,
  p_kompaniya_id bigint,
  p_loyiha_id bigint default null,
  p_obyekt_id bigint default null
)
returns jsonb
language plpgsql stable security definer set search_path=public,pg_temp as $$
declare
  v_rol text;
  v_company bigint;
  v_project bigint;
begin
  if p_actor_id is null or p_actor_id <= 0 then
    return jsonb_build_object('ok',false,'code','AUTH_REQUIRED');
  end if;
  if p_kompaniya_id is null then
    if p_loyiha_id is not null or p_obyekt_id is not null then
      return jsonb_build_object('ok',false,'code','SCOPE_LINEAGE_INVALID');
    end if;
    if not public.t2_platforma_superadmin(p_actor_id) then
      return jsonb_build_object('ok',false,'code','GLOBAL_SCOPE_DENIED');
    end if;
    return jsonb_build_object('ok',true,'rol','superadmin','scope','global');
  end if;

  begin
    v_rol := public.t2_actor_kompaniya_azo_tekshir(p_kompaniya_id,p_actor_id);
  exception when insufficient_privilege then
    return jsonb_build_object('ok',false,'code','COMPANY_ACCESS_DENIED');
  end;

  if p_loyiha_id is not null then
    select l.kompaniya_id into v_company from public.t2_loyiha l where l.id=p_loyiha_id;
    if v_company is null or v_company <> p_kompaniya_id then
      return jsonb_build_object('ok',false,'code','PROJECT_LINEAGE_INVALID');
    end if;
  end if;
  if p_obyekt_id is not null then
    select o.kompaniya_id, o.loyiha_id into v_company, v_project
      from public.t2_obyekt o where o.id=p_obyekt_id;
    if v_company is null or v_company <> p_kompaniya_id
       or (p_loyiha_id is not null and v_project <> p_loyiha_id) then
      return jsonb_build_object('ok',false,'code','OBJECT_LINEAGE_INVALID');
    end if;
  end if;
  return jsonb_build_object('ok',true,'rol',v_rol,'scope',case when p_obyekt_id is not null then 'object' when p_loyiha_id is not null then 'project' else 'company' end);
end $$;

create or replace function public.t2_agent_run_start_v1(
  p_actor_id bigint,
  p_agent_kod text,
  p_command_kod text,
  p_kompaniya_id bigint,
  p_loyiha_id bigint default null,
  p_obyekt_id bigint default null,
  p_operation_id uuid default null,
  p_input jsonb default '{}'::jsonb,
  p_requires_approval boolean default true
)
returns jsonb
language plpgsql security definer set search_path=public,pg_temp as $$
declare
  v_prev jsonb;
  v_profile public.t2_agent_profile%rowtype;
  v_guard jsonb;
  v_run public.t2_agent_run%rowtype;
  v_state text;
  v_requires_approval boolean;
  v_audit_company bigint;
  v_res jsonb;
begin
  if p_operation_id is null then return jsonb_build_object('ok',false,'code','OPERATION_ID_REQUIRED'); end if;
  select natija into v_prev from public.t2_agent_command_log where operation_id=p_operation_id;
  if found then return v_prev; end if;
  if coalesce(btrim(p_command_kod),'')='' then return jsonb_build_object('ok',false,'code','COMMAND_REQUIRED'); end if;
  if jsonb_typeof(coalesce(p_input,'{}'::jsonb)) not in ('object','array') then return jsonb_build_object('ok',false,'code','INPUT_INVALID'); end if;

  select * into v_profile from public.t2_agent_profile where kod=p_agent_kod and holat='active';
  if not found then return jsonb_build_object('ok',false,'code','AGENT_NOT_FOUND'); end if;
  if not (v_profile.allowed_commands ? btrim(p_command_kod)) then return jsonb_build_object('ok',false,'code','COMMAND_NOT_ALLOWED'); end if;
  v_guard := public.t2_agent_scope_guard_v1(p_actor_id,p_kompaniya_id,p_loyiha_id,p_obyekt_id);
  if coalesce((v_guard->>'ok')::boolean,false) is not true then return v_guard; end if;
  v_requires_approval := p_requires_approval or v_profile.permission_mode in ('command_prepare','human_approval_required');
  v_state := case when v_requires_approval then 'approval_required' else 'queued' end;

  insert into public.t2_agent_run(operation_id,agent_kod,actor_id,kompaniya_id,loyiha_id,obyekt_id,command_kod,holat,requires_approval,input)
  values (p_operation_id,p_agent_kod,p_actor_id,p_kompaniya_id,p_loyiha_id,p_obyekt_id,btrim(p_command_kod),v_state,v_requires_approval,coalesce(p_input,'{}'::jsonb))
  returning * into v_run;

  if v_requires_approval then
    insert into public.t2_agent_approval(run_id) values (v_run.id);
  end if;

  v_audit_company := p_kompaniya_id;
  if v_audit_company is null then
    select kompaniya_id into v_audit_company from public.t2_azolik
      where foydalanuvchi_id=p_actor_id and holat='faol' order by id limit 1;
  end if;
  perform public.t2_audit_yoz(v_audit_company,'agent_run_start','agent_control',null,
    format('run=%s agent=%s command=%s state=%s',v_run.id,p_agent_kod,p_command_kod,v_state),'actor:'||p_actor_id,null);
  v_res := jsonb_build_object('ok',true,'run_id',v_run.id,'operation_id',v_run.operation_id,'agent_kod',v_run.agent_kod,'holat',v_run.holat,'versiya',v_run.versiya,'requires_approval',v_run.requires_approval);
  insert into public.t2_agent_command_log(operation_id,actor_id,command,natija) values (p_operation_id,p_actor_id,'agent_run_start',v_res);
  return v_res;
exception when unique_violation then
  select jsonb_build_object('ok',true,'run_id',r.id,'operation_id',r.operation_id,'agent_kod',r.agent_kod,'holat',r.holat,'versiya',r.versiya,'requires_approval',r.requires_approval)
    into v_res from public.t2_agent_run r where r.operation_id=p_operation_id;
  if v_res is not null then return v_res; end if;
  raise;
end $$;

create or replace function public.t2_agent_run_transition_v1(
  p_actor_id bigint,
  p_run_id bigint,
  p_new_holat text,
  p_expected_version integer,
  p_operation_id uuid,
  p_result jsonb default null,
  p_error_code text default null,
  p_error_detail text default null
)
returns jsonb
language plpgsql security definer set search_path=public,pg_temp as $$
declare
  v_prev jsonb;
  v_run public.t2_agent_run%rowtype;
  v_guard jsonb;
  v_allowed boolean := false;
  v_res jsonb;
begin
  if p_operation_id is null then return jsonb_build_object('ok',false,'code','OPERATION_ID_REQUIRED'); end if;
  select natija into v_prev from public.t2_agent_command_log where operation_id=p_operation_id;
  if found then return v_prev; end if;
  select * into v_run from public.t2_agent_run where id=p_run_id for update;
  if not found then return jsonb_build_object('ok',false,'code','RUN_NOT_FOUND'); end if;
  v_guard := public.t2_agent_scope_guard_v1(p_actor_id,v_run.kompaniya_id,v_run.loyiha_id,v_run.obyekt_id);
  if coalesce((v_guard->>'ok')::boolean,false) is not true then return v_guard; end if;
  if p_actor_id <> v_run.actor_id and coalesce(v_guard->>'rol','') not in ('boss','rahbar','superadmin') then
    return jsonb_build_object('ok',false,'code','RUN_PERMISSION_DENIED');
  end if;
  if p_expected_version is null or p_expected_version <> v_run.versiya then
    return jsonb_build_object('ok',false,'code','STALE_VERSION','versiya',v_run.versiya,'holat',v_run.holat);
  end if;

  v_allowed := (v_run.holat,p_new_holat) in (
    ('queued','running'),('queued','cancelled'),('approval_required','queued'),
    ('approval_required','cancelled'),('running','waiting_review'),('running','applying'),
    ('running','exporting'),('running','completed'),('running','failed'),('running','cancelled'),
    ('waiting_review','queued'),('waiting_review','cancelled'),('applying','completed'),
    ('applying','failed'),('applying','cancelled'),('exporting','completed'),('exporting','failed'),
    ('exporting','cancelled'),('failed','queued'),('failed','cancelled')
  );
  if not v_allowed then return jsonb_build_object('ok',false,'code','RUN_TRANSITION_INVALID','from',v_run.holat,'to',p_new_holat); end if;

  update public.t2_agent_run set holat=p_new_holat, result=coalesce(p_result,result), error_code=p_error_code,
    error_detail=p_error_detail, versiya=versiya+1, started_at=case when p_new_holat='running' then coalesce(started_at,now()) else started_at end,
    finished_at=case when p_new_holat in ('completed','failed','cancelled') then now() else finished_at end, updated_at=now()
    where id=p_run_id;
  perform public.t2_audit_yoz(v_run.kompaniya_id,'agent_run_transition','agent_control',null,
    format('run=%s %s->%s',p_run_id,v_run.holat,p_new_holat),'actor:'||p_actor_id,null);
  v_res := jsonb_build_object('ok',true,'run_id',p_run_id,'holat',p_new_holat,'versiya',v_run.versiya+1);
  insert into public.t2_agent_command_log(operation_id,actor_id,command,natija) values (p_operation_id,p_actor_id,'agent_run_transition',v_res);
  return v_res;
end $$;

create or replace function public.t2_agent_approval_decide_v1(
  p_actor_id bigint,
  p_run_id bigint,
  p_decision text,
  p_sabab text,
  p_expected_version integer,
  p_operation_id uuid
)
returns jsonb
language plpgsql security definer set search_path=public,pg_temp as $$
declare
  v_prev jsonb;
  v_run public.t2_agent_run%rowtype;
  v_guard jsonb;
  v_res jsonb;
begin
  if p_operation_id is null then return jsonb_build_object('ok',false,'code','OPERATION_ID_REQUIRED'); end if;
  select natija into v_prev from public.t2_agent_command_log where operation_id=p_operation_id;
  if found then return v_prev; end if;
  if p_decision not in ('approve','reject') then return jsonb_build_object('ok',false,'code','APPROVAL_DECISION_INVALID'); end if;
  if p_decision='reject' and coalesce(btrim(p_sabab),'')='' then return jsonb_build_object('ok',false,'code','REJECTION_REASON_REQUIRED'); end if;
  select * into v_run from public.t2_agent_run where id=p_run_id for update;
  if not found then return jsonb_build_object('ok',false,'code','RUN_NOT_FOUND'); end if;
  v_guard := public.t2_agent_scope_guard_v1(p_actor_id,v_run.kompaniya_id,v_run.loyiha_id,v_run.obyekt_id);
  if coalesce((v_guard->>'ok')::boolean,false) is not true then return v_guard; end if;
  if coalesce(v_guard->>'rol','') not in ('boss','rahbar','superadmin') then return jsonb_build_object('ok',false,'code','APPROVAL_PERMISSION_DENIED'); end if;
  if p_expected_version is null or p_expected_version <> v_run.versiya then return jsonb_build_object('ok',false,'code','STALE_VERSION','versiya',v_run.versiya); end if;
  if v_run.holat <> 'approval_required' then return jsonb_build_object('ok',false,'code','APPROVAL_NOT_PENDING','holat',v_run.holat); end if;

  update public.t2_agent_approval set holat=case when p_decision='approve' then 'approved' else 'rejected' end,
    decided_at=now(), decided_by=p_actor_id, sabab=p_sabab, versiya=versiya+1 where run_id=p_run_id;
  update public.t2_agent_run set holat=case when p_decision='approve' then 'queued' else 'cancelled' end,
    result=case when p_decision='reject' then jsonb_build_object('decision','rejected','sabab',p_sabab) else result end,
    versiya=versiya+1, finished_at=case when p_decision='reject' then now() else null end, updated_at=now() where id=p_run_id;
  perform public.t2_audit_yoz(v_run.kompaniya_id,'agent_approval_'||p_decision,'agent_control',null,
    format('run=%s decision=%s',p_run_id,p_decision),'actor:'||p_actor_id,null);
  v_res := jsonb_build_object('ok',true,'run_id',p_run_id,'decision',p_decision,'holat',case when p_decision='approve' then 'queued' else 'cancelled' end,'versiya',v_run.versiya+1);
  insert into public.t2_agent_command_log(operation_id,actor_id,command,natija) values (p_operation_id,p_actor_id,'agent_approval_decide',v_res);
  return v_res;
end $$;

create or replace function public.t2_agent_tool_call_prepare_v1(
  p_actor_id bigint,
  p_run_id bigint,
  p_tool_kod text,
  p_request jsonb,
  p_operation_id uuid,
  p_sequence_no integer default null
)
returns jsonb
language plpgsql security definer set search_path=public,pg_temp as $$
declare
  v_prev jsonb;
  v_run public.t2_agent_run%rowtype;
  v_profile public.t2_agent_profile%rowtype;
  v_guard jsonb;
  v_seq integer;
  v_call public.t2_agent_tool_call%rowtype;
  v_res jsonb;
begin
  if p_operation_id is null then return jsonb_build_object('ok',false,'code','OPERATION_ID_REQUIRED'); end if;
  select natija into v_prev from public.t2_agent_command_log where operation_id=p_operation_id;
  if found then return v_prev; end if;
  select * into v_run from public.t2_agent_run where id=p_run_id for update;
  if not found then return jsonb_build_object('ok',false,'code','RUN_NOT_FOUND'); end if;
  select * into v_profile from public.t2_agent_profile where kod=v_run.agent_kod;
  v_guard := public.t2_agent_scope_guard_v1(p_actor_id,v_run.kompaniya_id,v_run.loyiha_id,v_run.obyekt_id);
  if coalesce((v_guard->>'ok')::boolean,false) is not true then return v_guard; end if;
  if v_run.holat = 'approval_required' then return jsonb_build_object('ok',false,'code','AGENT_APPROVAL_REQUIRED'); end if;
  if v_run.holat in ('completed','cancelled','failed') then return jsonb_build_object('ok',false,'code','RUN_NOT_ACTIVE','holat',v_run.holat); end if;
  if p_actor_id <> v_run.actor_id and coalesce(v_guard->>'rol','') not in ('boss','rahbar','superadmin') then return jsonb_build_object('ok',false,'code','RUN_PERMISSION_DENIED'); end if;
  if not (v_profile.allowed_tools ? p_tool_kod) then return jsonb_build_object('ok',false,'code','TOOL_NOT_ALLOWED','tool_kod',p_tool_kod); end if;
  select coalesce(p_sequence_no,max(sequence_no)+1) into v_seq from public.t2_agent_tool_call where run_id=p_run_id;
  insert into public.t2_agent_tool_call(run_id,sequence_no,operation_id,actor_id,tool_kod,request)
    values(p_run_id,v_seq,p_operation_id,p_actor_id,p_tool_kod,coalesce(p_request,'{}'::jsonb)) returning * into v_call;
  v_res := jsonb_build_object('ok',true,'tool_call_id',v_call.id,'run_id',p_run_id,'sequence_no',v_call.sequence_no,'tool_kod',v_call.tool_kod,'holat',v_call.holat);
  insert into public.t2_agent_command_log(operation_id,actor_id,command,natija) values (p_operation_id,p_actor_id,'agent_tool_call_prepare',v_res);
  return v_res;
exception when unique_violation then
  select jsonb_build_object('ok',true,'tool_call_id',c.id,'run_id',c.run_id,'sequence_no',c.sequence_no,'tool_kod',c.tool_kod,'holat',c.holat)
    into v_res from public.t2_agent_tool_call c where c.operation_id=p_operation_id;
  if v_res is not null then return v_res; end if;
  raise;
end $$;

create or replace function public.t2_agent_control_v1(
  p_actor_id bigint,
  p_kompaniya_id bigint default null,
  p_limit integer default 50
)
returns jsonb
language plpgsql stable security definer set search_path=public,pg_temp as $$
declare
  v_guard jsonb;
  v_agents jsonb;
  v_runs jsonb;
  v_approvals jsonb;
  v_lim integer := greatest(1,least(coalesce(p_limit,50),100));
begin
  v_guard := public.t2_agent_scope_guard_v1(p_actor_id,p_kompaniya_id,null,null);
  if coalesce((v_guard->>'ok')::boolean,false) is not true then return v_guard; end if;
  select coalesce(jsonb_agg(jsonb_build_object('kod',p.kod,'nom',p.nom,'rol',p.rol,'permission_mode',p.permission_mode,'allowed_commands',p.allowed_commands,'allowed_tools',p.allowed_tools,'default_scope',p.default_scope,'holat',p.holat,'versiya',p.versiya) order by p.kod),'[]'::jsonb) into v_agents from public.t2_agent_profile p;
  select coalesce(jsonb_agg(q.x order by q.created_at desc),'[]'::jsonb) into v_runs from (
    select jsonb_build_object('run_id',r.id,'operation_id',r.operation_id,'agent_kod',r.agent_kod,'command_kod',r.command_kod,'holat',r.holat,'kompaniya_id',r.kompaniya_id,'loyiha_id',r.loyiha_id,'obyekt_id',r.obyekt_id,'versiya',r.versiya,'created_at',r.created_at,'updated_at',r.updated_at) as x, r.created_at
    from public.t2_agent_run r where (p_kompaniya_id is null or r.kompaniya_id=p_kompaniya_id) order by r.created_at desc limit v_lim
  ) q;
  select coalesce(jsonb_agg(q.x order by q.requested_at desc),'[]'::jsonb) into v_approvals from (
    select jsonb_build_object('run_id',a.run_id,'holat',a.holat,'requested_at',a.requested_at,'sabab',a.sabab) as x, a.requested_at
    from public.t2_agent_approval a join public.t2_agent_run r on r.id=a.run_id
    where a.holat='pending' and (p_kompaniya_id is null or r.kompaniya_id=p_kompaniya_id) order by a.requested_at desc limit v_lim
  ) q;
  return jsonb_build_object('ok',true,'agents',v_agents,'runs',v_runs,'approvals',v_approvals,'scope',v_guard->>'scope');
end $$;

revoke all on public.t2_agent_profile, public.t2_agent_run, public.t2_agent_approval, public.t2_agent_tool_call, public.t2_agent_command_log from public, anon, authenticated;
alter table public.t2_agent_profile enable row level security;
alter table public.t2_agent_run enable row level security;
alter table public.t2_agent_approval enable row level security;
alter table public.t2_agent_tool_call enable row level security;
alter table public.t2_agent_command_log enable row level security;

revoke all on function public.t2_agent_scope_guard_v1(bigint,bigint,bigint,bigint) from public, anon, authenticated;
revoke all on function public.t2_agent_run_start_v1(bigint,text,text,bigint,bigint,bigint,uuid,jsonb,boolean) from public, anon, authenticated;
revoke all on function public.t2_agent_run_transition_v1(bigint,bigint,text,integer,uuid,jsonb,text,text) from public, anon, authenticated;
revoke all on function public.t2_agent_approval_decide_v1(bigint,bigint,text,text,integer,uuid) from public, anon, authenticated;
revoke all on function public.t2_agent_tool_call_prepare_v1(bigint,bigint,text,jsonb,uuid,integer) from public, anon, authenticated;
revoke all on function public.t2_agent_control_v1(bigint,bigint,integer) from public, anon, authenticated;
grant execute on function public.t2_agent_scope_guard_v1(bigint,bigint,bigint,bigint) to service_role;
grant execute on function public.t2_agent_run_start_v1(bigint,text,text,bigint,bigint,bigint,uuid,jsonb,boolean) to service_role;
grant execute on function public.t2_agent_run_transition_v1(bigint,bigint,text,integer,uuid,jsonb,text,text) to service_role;
grant execute on function public.t2_agent_approval_decide_v1(bigint,bigint,text,text,integer,uuid) to service_role;
grant execute on function public.t2_agent_tool_call_prepare_v1(bigint,bigint,text,jsonb,uuid,integer) to service_role;
grant execute on function public.t2_agent_control_v1(bigint,bigint,integer) to service_role;

comment on table public.t2_agent_run is 'Agent execution receipt only; canonical business commands remain domain-owned and human-approved when required.';
comment on table public.t2_agent_tool_call is 'Allowlisted tool preparation/audit; no arbitrary SQL or unregistered side effect.';

commit;
